### ISSUE TITLE
Typo in 6.fp-pure-functions.js

### ISSUE THREAD

**Issue by tbassetto** [airportyh/word-count#1]
I didn't bother creating a PR just for that but on https://github.com/airportyh/word-count/blob/5eb792feb0a0b5c4dc8402f073fad08286879976/6.fp-pure-functions.js#L21 either the argument name should be `content` or the next line should use `text` :)

**Comment by tbassetto** [comment]
Also typo on this line: https://github.com/airportyh/word-count/blob/5eb792feb0a0b5c4dc8402f073fad08286879976/7.fp-pure-but-slow.js#L7

**Comment by airportyh** [comment]
Thank you!
